project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "*.ipynb"
    - "reference/*.qmd"


quartodoc:
  package: geospatial_toolkit
  dir: reference        
  sections:
    - title: API Reference
      desc: Detailed documentation for the geospatial functions.
      contents:
        - calc_antipode.get_antipode
        - distance.haversine_distance
        - latlong.standardize_latlong
        - point_to_city.point_to_city


website:
  title: "Geospatial Toolkit" 
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Tutorial"   
        href: demo.ipynb      
      - text: "Reference"
        href: reference/index.qmd


format:
  html:
    theme: cosmo
    code-fold: true     
    toc: true               